algorithm:
  default: distance
  type:
    distance:
      # At which distance should we open elytra
      threshold: 4.0
    damage:
      # At how much potential health should we open elytra
      threshold: 4 # Two hearts

version: 2
