name: SafeElytra
version: '${version}'
main: com.github.kaspiandev.safeelytra.SafeElytra
api-version: '1.19'
author: KaspianDev
libraries:
  - dev.dejvokep:boosted-yaml:1.3.5
permissions:
  safeelytra.use:
    default: op
